spring.application.name=firstproject

server.port = 8080

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/korko
spring.datasource.username=postgres
spring.datasource.password=oudom
spring.datasource.driverClassName=org.postgresql.Driver

# Enable H2 console only if needed for local testing
spring.h2.console.enabled=false

# JPA settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:h2:mem:telusko
#spring.datasource.driverClassName=org.h2.Driver
#
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.defer-datasource-initialization=true
